// Mocks generated by Mockito 5.4.6 from annotations
// in kindergarten_frontend/test/screens/test_staff_screen.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:kindergarten_frontend/models/staff.dart' as _i3;
import 'package:kindergarten_frontend/providers/staff_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StaffProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockStaffProvider extends _i1.Mock implements _i2.StaffProvider {
  MockStaffProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Staff> get staff =>
      (super.noSuchMethod(Invocation.getter(#staff), returnValue: <_i3.Staff>[])
          as List<_i3.Staff>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadStaff() =>
      (super.noSuchMethod(
            Invocation.method(#loadStaff, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addStaff(_i3.Staff? staff) =>
      (super.noSuchMethod(
            Invocation.method(#addStaff, [staff]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateStaff(_i3.Staff? staff) =>
      (super.noSuchMethod(
            Invocation.method(#updateStaff, [staff]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteStaff(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStaff, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i3.Staff> getTeachers() =>
      (super.noSuchMethod(
            Invocation.method(#getTeachers, []),
            returnValue: <_i3.Staff>[],
          )
          as List<_i3.Staff>);

  @override
  _i3.Staff? getStaffById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getStaffById, [id]))
          as _i3.Staff?);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
